version: '3.1'

services:
    wp_php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '666:80'
        volumes:
            - ./wordpress:/var/www/html

    wp_db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: pass
        volumes:
            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

    wp_pma:
        image: phpmyadmin
        restart: always
        ports:
            - '777:80'
        environment:
            - PMA_ARBITRARY=1
