services:
    wp_php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '666:80'
        volumes:
            - ./wordpress:/var/www/html
        networks:
            - wp-net

    wp_db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: pass
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - wp-net

    wp_pma:
        image: phpmyadmin
        restart: always
        ports:
            - '777:80'
        depends_on:
            - wp_db
        environment:
            - PMA_ARBITRARY=1
        networks:
            - wp-net

networks:
    wp-net:
